# Reading images in Python

For this notebook, you will need the Python Imaging Library, PIL, installed.
This allows you to easily import images and manipulate the data in Python.

The first thing you will need to do is import the Image module from PIL, as well as NumPy for easy data manipulation:

In [18]:
from PIL import Image
import numpy as np


From here, there is a very simple command to import an image by its path. 
Most commonly used image formats, in our case particularly PNG and JPEG, are read in without any extra work:

In [19]:
im = Image.open('cameraman.png')
im.show()

Next, you can use the getdata() function to get the numerical values for pixels. 
This data object can then be converted to a Python list or a NumPy array.

In [20]:
imlist = list(im.getdata())
print(imlist[0:10])
imarray = np.array(im.getdata())
print(imarray[0:10])

[156, 159, 158, 155, 158, 156, 159, 158, 157, 158]
[156 159 158 155 158 156 159 158 157 158]


You may notice that this list or array is one-dimensional.
If this image were RGB, there would be a tuple of 3 values for each element in the list or array.
However, this still would be an essentially one-dimensional representation of a two-dimensional image.
This can easily be resolved by using NumPy's reshape command, combined with the size attribute of the original Image object.

In [21]:
print(im.size)
imarray2d = np.reshape(imarray, im.size)
print(imarray2d)
imlist2d = np.reshape(imlist, im.size)
print(imlist2d)

(256, 256)
[[156 159 158 ..., 151 152 152]
 [160 154 157 ..., 154 155 153]
 [156 159 158 ..., 151 152 152]
 ..., 
 [114 132 123 ..., 135 137 114]
 [121 126 130 ..., 133 130 113]
 [121 126 130 ..., 133 130 113]]
[[156 159 158 ..., 151 152 152]
 [160 154 157 ..., 154 155 153]
 [156 159 158 ..., 151 152 152]
 ..., 
 [114 132 123 ..., 135 137 114]
 [121 126 130 ..., 133 130 113]
 [121 126 130 ..., 133 130 113]]


For the sake of clarity, here you can see the same process using NumPy arrays for a color JPEG image.
The process is the same, but a little different process is used for reshaping.
This is because the size attribute refers to the number of pixels in each dimension. So, to reshape this properly you need to add the third dimension, which will be of size 3.

In [22]:
imcolor = Image.open('smile.jpeg')
imcolorarray = np.array(imcolor)
print(imcolor.size)
imcolorarray2d = np.reshape(imcolorarray, [imcolor.size[0],imcolor.size[1], 3])
print(imcolorarray2d)

(256, 256)
[[[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]

 [[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]

 [[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]

 ..., 
 [[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]

 [[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]

 [[ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]
  ..., 
  [ 65 179 252]
  [ 65 179 252]
  [ 65 179 252]]]


You can also use the Image module of PIL to reconstruct an image from an array or list:

In [23]:
newcolorImage = Image.fromarray(imcolorarray2d)
newcolorImage.show()

Finally, these images can be exported to real image files using the write command.
The file extension automatically determines the file type to be written.
You can also use a file pointer or handle rather than a filename as the argument.

In [24]:
newcolorImage.save('new.jpg')
newcolorImage.save('new.png')